### ISSUE TITLE
Commands missing?

### ISSUE THREAD

**Issue by HageMaster3108** [CI-HUB-GmbH/SimpleRESTAdapterBundle#1]
Using SimpleRESTAdapterBundle (tested 1.0.0 on pimcore 6.9 and 2.0.0 on pimcore X, all from composer/packagist) it seems that the classes defined in `commands.yml` are missing, which quite quickly surfaces by breaking `bin/console`, which throws the following (e.g. by just running `bin/console` without arguments):
```
In getCreateOrUpdateMappingCommandService.php line 9:

  Attempted to load class "CreateOrUpdateMappingCommand" from namespace "CIHub\Bundle\SimpleRESTAdapterBundle\Command".
  Did you forget a "use" statement for another namespace?
```
In fact I can find none of the Command classes defined in the config in the repo?

Thanks,
Patrick

**Comment by aarongerig** [comment]
Thanks for the report. You are right, that's a left over from development that shouldn't be there. We'll have to remove those service configurations.

**Comment by HageMaster3108** [comment]
Thanks for your response @aarongerig ;-)
However I stumbled over this because I was looking for a way to force a re-index and thought these commands might be useful? Is that possible somehow? My index looks broken (using the CI HUB connector on top of this and I only see a fraction of my assets).

**Comment by aarongerig** [comment]
That would definitely be possible somehow, @HageMaster3108 ! Do you wanna take a shot and try to create a PR for such a command?

**Comment by aarongerig** [comment]
Fixed by https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/commit/6887e954d09588d763224c0756b0c217f3981877

@HageMaster3108 If you're still interested in having such a command to re-index all items, please create either another issue/feature request or you can give it a try yourself and prepare a pull-request for it. Would be much appreciated! :)
