### ISSUE TITLE
Problem with fetching single elements through rest API

### ISSUE THREAD

**Issue by xfynx** [CI-HUB-GmbH/SimpleRESTAdapterBundle#2]
Hello everyone!
I'm trying to configure the bundle and faced strange issue.

Source: https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/blame/master/src/SimpleRESTAdapterBundle/Controller/EndpointController.php#L146

For some reason for successful data finding it uses dd function. As far as i can see (i'm not a php expert), it means "dump and die" (and immediately end the script), which leads to 500 error. When i commented the line, i had successful response as expected.
https://github.com/symfony/var-dumper/commit/a60e015a49db26dda873ca3ef74776db65f5e709

Is it some kind of debug logic which wasn't removed? Or is it something that i can't understand properly (and how to deal with it then)?

Thanks in advance!

**Comment by aarongerig** [comment]
Hi @xfynx,

You are totally correct, that `dd()` statement shouldn't be there as it was used for debugging purposes. We'll have to remove that.

Thank you for the report!

**Comment by aarongerig** [comment]
Fixed by https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/commit/bc2550bd5cde4383186c6f46eb91065b716c98de

**Comment by xfynx** [comment]
wow, so fast, thank you!
