### ISSUE TITLE
Elements are not deleted from ES index

### ISSUE THREAD

**Issue by birgerstoeckelmann** [CI-HUB-GmbH/SimpleRESTAdapterBundle#6]
Assets that are deleted via the Pimcore backend are not deleted from the Elasticsearch index.

The message DeleteIndexElementMessage seems to get invoked after the asset is deleted from the database. Hence the element identified by the message parameters is null.

Pimcore: 10.5.2
ci-hub/simple-rest-adapter-bundle: 2.0.1
ci-hub/pimcore-ci-hub-adapter-bundle: 2.0.1
symfony/doctrine-messenger: 5.4.11
elasticsearch: 7.17.1

**Comment by aarongerig** [comment]
Thanks for reporting this issue! I'll have a look into that asap.

**Comment by aarongerig** [comment]
Fixed by https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/commit/ae92f55e3f1b02ab06bd5cbe052f1ba24323de70

**Comment by birgerstoeckelmann** [comment]
I'm sorry to reopen this, but the fix stopped working with Pimcore 10.5.3.

Elements are not deleted from ES index after removing them via the Pimcore backend.

Pimcore: 10.5.3
ci-hub/simple-rest-adapter-bundle: 2.0.2
ci-hub/pimcore-ci-hub-adapter-bundle: 2.0.1
symfony/doctrine-messenger: 5.4.12
elasticsearch: 7.17.1

**Comment by aarongerig** [comment]
@birgerstoeckelmann Are you sure about that? Nothing has changed regarding deleting assets/objects in Pimcore from 10.5.2 to 10.5.3. Maybe it is something related to you setup?

**Comment by birgerstoeckelmann** [comment]
@aarongerig - Not, not really, because the fix worked very well in 10.5.2. I cleared pimcore and symfony caches and made sure that the RESTBundle version is 2.0.2 (still installing from github).

The VersionDeleteMessage seems to be handled first when checking the messenger queue output:

11:35:13 INFO      [messenger] Received message Pimcore\Messenger\VersionDeleteMessage ["class" => "Pimcore\Messenger\VersionDeleteMessage"]
11:35:13 INFO      [messenger] Message Pimcore\Messenger\VersionDeleteMessage handled by Pimcore\Messenger\Handler\VersionDeleteHandler::__invoke ["class" => "Pimcore\Messenger\VersionDeleteMessage","handler" => "Pimcore\Messenger\Handler\VersionDeleteHandler::__invoke"]
11:35:13 INFO      [messenger] Received message CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage ["class" => "CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage"]
11:35:13 INFO      [messenger] Message CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage handled by CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\Handler\DeleteIndexElementMessageHandler::__invoke ["class" => "CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage","handler" => "CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\Handler\DeleteIndexElementMessageHandler::__invoke"]
11:35:13 INFO      [messenger] CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage was handled successfully (acknowledging to transport). ["class" => "CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage"]
11:35:14 INFO      [messenger] Received message Pimcore\Messenger\VersionDeleteMessage ["class" => "Pimcore\Messenger\VersionDeleteMessage"]
11:35:14 INFO      [php] User Deprecated: Method "Iterator::key()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Aws\ResultPaginator" now to avoid errors or add an explicit @return annotation to suppress this message. ["exception" => ErrorException { …}]
11:35:14 INFO      [php] User Deprecated: Method "Iterator::next()" might add "void" as a native return type declaration in the future. Do the same in implementation "Aws\ResultPaginator" now to avoid errors or add an explicit @return annotation to suppress this message. ["exception" => ErrorException { …}]
11:35:14 INFO      [php] User Deprecated: Method "Iterator::valid()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Aws\ResultPaginator" now to avoid errors or add an explicit @return annotation to suppress this message. ["exception" => ErrorException { …}]
11:35:14 INFO      [php] User Deprecated: Method "Iterator::rewind()" might add "void" as a native return type declaration in the future. Do the same in implementation "Aws\ResultPaginator" now to avoid errors or add an explicit @return annotation to suppress this message. ["exception" => ErrorException { …}]
11:35:14 INFO      [messenger] Pimcore\Messenger\VersionDeleteMessage was handled successfully (acknowledging to transport). ["class" => "Pimcore\Messenger\VersionDeleteMessage"]

**Comment by aarongerig** [comment]
@birgerstoeckelmann It doesn't matter, if the `Pimcore\Messenger\VersionDeleteMessage` is handled first or before our `CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage`. The messages payload is stored as a serialized PHP array in the database. Therefore the asset/object ID should be present in the DB.

Could you check if the asset/object ID gets stored in the message body in your database and if that ID is present in your Elasticsearch index? Thank you!

**Comment by birgerstoeckelmann** [comment]
@aarongerig I downgraded to Pimcore 10.5.2 and it is **not** working again (sometimes the item is deleted, sometimes not).

The deletion method of src/SimpleRESTAdapterBundle/Messenger/Handler/DeleteIndexElementMessageHandler.php

```
    /**
    * @param DeleteIndexElementMessage $message
    */
    public function __invoke(DeleteIndexElementMessage $message): void
    {
        switch ($message->getEntityType()) {
            case 'asset':
                $element = Asset::getById($message->getEntityId());
                break;
            case 'object':
                $element = DataObject\AbstractObject::getById($message->getEntityId());
                break;
            default:
                $element = null;
        }
```

tries to get the asset from the database again to check, if it's a valid entity, but the asset could already be deleted at this point and $element is null?

As far as I understand your code the event "PRE_DELETE" from your latest fix is used for enqueuing the mesage with the asset id (entityId) before the asset is deleted. But here on "__invoke" (later, when the message is processed) the id is used to fetch the asset from the database again?

The message body contains the correct asset id (entityId):
O:36:\"Symfony\\Component\\Messenger\\Envelope\":2:{s:44:\"\0Symfony\\Component\\Messenger\\Envelope\0stamps\";a:1:{s:46:\"Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\";a:1:{i:0;O:46:\"Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\":1:{s:55:\"\0Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\0busName\";s:26:\"messenger.bus.pimcore-core\";}}}s:45:\"\0Symfony\\Component\\Messenger\\Envelope\0message\";O:72:\"CIHub\\Bundle\\SimpleRESTAdapterBundle\\Messenger\\DeleteIndexElementMessage\":3:{s:82:\"\0CIHub\\Bundle\\SimpleRESTAdapterBundle\\Messenger\\DeleteIndexElementMessage\0entityId\";i:65085;s:84:\"\0CIHub\\Bundle\\SimpleRESTAdapterBundle\\Messenger\\DeleteIndexElementMessage\0entityType\";s:5:\"asset\";s:86:\"\0CIHub\\Bundle\\SimpleRESTAdapterBundle\\Messenger\\DeleteIndexElementMessage\0endpointName\";s:11:\"ci-demo-hub\";}}

**Comment by aarongerig** [comment]
@birgerstoeckelmann Yes, you are right. I have to completely refactor that and only pass the ID instead of the whole element to the index service. Sorry for the trouble!

**Comment by birgerstoeckelmann** [comment]
@aarongerig No problem, thanks for looking into it and your quick responses. Really a great support, appreciate that!

**Comment by aarongerig** [comment]
Resolved by https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/commit/f8a632bb0972069efafd9fdd640790d6a1454593

**Comment by aarongerig** [comment]
@birgerstoeckelmann This should be good now. I'll make another release once I have a solution for [this issue](https://github.com/CI-HUB-GmbH/PimcoreCIHubAdapterBundle/issues/2) as well.
