### ISSUE TITLE
datahub_es_index_queue needs proper configuration in framework

### ISSUE THREAD

**Issue by birgerstoeckelmann** [CI-HUB-GmbH/SimpleRESTAdapterBundle#7]
Without overwriting the messenger.transports.datahub_es_index_queue configuration in Pimcore's config/config.yaml the messenger throws exceptions for all messages:

` Error thrown while handling message Pimcore\Messenger\SearchBackendMessage. Sending for retry #1 using 1000 ms delay. Error: "Bus named "messenger.bus.default" does not exist." ["class" => "Pimcore\Messenger\SearchBackendMessage","retryCount" => 1,"delay" => 1000,"error" => "Bus named "messenger.bus.default" does not exist.","exception" => Symfony\Component\Messenger\Exception\InvalidArgumentException^ { …}]`

This configuration works:

framework:
&nbsp;&nbsp;messenger:
&nbsp;&nbsp;&nbsp;&nbsp;transports:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;datahub_es_index_queue: "doctrine://default?queue_name=datahub_es_index_queue"

Pimcore: 10.5.2
ci-hub/simple-rest-adapter-bundle: 2.0.1
ci-hub/pimcore-ci-hub-adapter-bundle: 2.0.1
symfony/doctrine-messenger: 5.4.11
elasticsearch: 7.17.1

**Comment by aarongerig** [comment]
Thanks for reporting this issue! I will take a look at that problem as well.

**Comment by aarongerig** [comment]
Fixed by https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/commit/17c4425d95e1434be9dbf58101b0811991985309

**Comment by aarongerig** [comment]
@birgerstoeckelmann I just released [v2.0.2](https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/releases/tag/v2.0.2), which includes both fixes. Could you verify if that works for you now?

**Comment by birgerstoeckelmann** [comment]
@aarongerig - yes, both fixes work as expected. Thanks for fixing this so quickly!
